### Register User
POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "userbaru",
  "email": "userbaru@example.com",
  "password": "password123"
}

### Login User
POST http://localhost:5000/login
Content-Type: application/json

{
  "usernameOrEmail": "userbaru",
  "password": "password123"
}

### Get All Notes
GET http://localhost:5000/notes
Authorization: Bearer <accessToken>

### Create New Note
POST http://localhost:5000/notes
Content-Type: application/json
Authorization: Bearer <accessToken>

{
  "judul": "Catatan bersejarah",
  "deskripsi": "Hari ini saya belajar dasar dasar backend."
}

### Update Note By ID
PUT http://localhost:5000/notes/12
Content-Type: application/json
Authorization: Bearer <accessToken>

{
  "judul": "Catatan Perjalanan",
  "deskripsi": "Saya melakukan perjalanan ke gunung dan menikmati keindahan alam."
}

### Delete Note By ID
DELETE http://localhost:5000/notes/12
Authorization: Bearer <accessToken>

